export const alpacaConfig = [
	{
		id: 0,
		label: 'backgrounds',
		directory: 'backgrounds',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{ id: 1, label: 'blue 60', fileName: 'blue60', selected: false },
			{ id: 2, label: 'blue 70', fileName: 'blue70', selected: false },
			{ id: 3, label: 'darkblue 30', fileName: 'darkblue30', selected: false },
			{ id: 4, label: 'darkblue 50', fileName: 'darkblue50', selected: false },
			{ id: 5, label: 'darkblue 70', fileName: 'darkblue70', selected: false },
			{ id: 6, label: 'green 50', fileName: 'green50', selected: false },
			{ id: 7, label: 'green 60', fileName: 'green60', selected: false },
			{ id: 8, label: 'green 70', fileName: 'green70', selected: false },
			{ id: 9, label: 'grey 40', fileName: 'grey40', selected: false },
			{ id: 10, label: 'grey 70', fileName: 'grey70', selected: false },
			{ id: 11, label: 'grey 80', fileName: 'grey80', selected: false },
			{ id: 12, label: 'red 50', fileName: 'red50', selected: false },
			{ id: 13, label: 'red 60', fileName: 'red60', selected: false },
			{ id: 14, label: 'red 70', fileName: 'red70', selected: false },
			{ id: 15, label: 'yellow 50', fileName: 'yellow50', selected: false },
			{ id: 16, label: 'yellow 60', fileName: 'yellow60', selected: false },
			{ id: 17, label: 'yellow 70', fileName: 'yellow70', selected: false },
		],
	},
	{
		id: 1,
		label: 'ears',
		directory: 'ears',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{
				id: 1,
				label: 'tilt backward',
				fileName: 'tilt-backward',
				selected: false,
			},
			{
				id: 2,
				label: 'tilt forward',
				fileName: 'tilt-forward',
				selected: false,
			},
		],
	},
	{
		id: 2,
		label: 'eyes',
		directory: 'eyes',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{ id: 1, label: 'angry', fileName: 'angry', selected: false },
			{ id: 2, label: 'naughty', fileName: 'naughty', selected: false },
			{ id: 3, label: 'panda', fileName: 'panda', selected: false },
			{ id: 4, label: 'smart', fileName: 'smart', selected: false },
		],
	},
	{
		id: 3,
		label: 'hair',
		directory: 'hair',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{ id: 1, label: 'bang', fileName: 'bang', selected: false },
			{ id: 2, label: 'curls', fileName: 'curls', selected: false },
			{ id: 3, label: 'elegant', fileName: 'elegant', selected: false },
			{ id: 4, label: 'fancy', fileName: 'fancy', selected: false },
			{ id: 5, label: 'quiff', fileName: 'quiff', selected: false },
			{ id: 6, label: 'short', fileName: 'short', selected: false },
		],
	},
	{
		id: 4,
		label: 'leg',
		directory: 'leg',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{ id: 1, label: 'bubble tea', fileName: 'bubble-tea', selected: false },
			{
				id: 2,
				label: 'game-console',
				fileName: 'game-console',
				selected: false,
			},
			{
				id: 3,
				label: 'tilt-forward',
				fileName: 'tilt-forward',
				selected: false,
			},
			{
				id: 4,
				label: 'tilt-backward',
				fileName: 'tilt-backward',
				selected: false,
			},
		],
	},
	{
		id: 5,
		label: 'mouth',
		directory: 'mouth',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{ id: 1, label: 'astonished', fileName: 'astonished', selected: false },
			{ id: 2, label: 'eating', fileName: 'eating', selected: false },
			{ id: 3, label: 'laugh', fileName: 'laugh', selected: false },
			{ id: 4, label: 'tongue', fileName: 'tongue', selected: false },
		],
	},
	{
		id: 6,
		label: 'neck',
		directory: 'neck',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{
				id: 1,
				label: 'bend-backward',
				fileName: 'bend-backward',
				selected: false,
			},
			{
				id: 2,
				label: 'bend forward',
				fileName: 'bend-forward',
				selected: false,
			},
			{ id: 3, label: 'thick', fileName: 'thick', selected: false },
		],
	},

	{
		id: 7,
		label: 'nose',
		directory: 'nose',
		selected: false,
		items: [{ id: 0, label: 'default', fileName: 'default', selected: false }],
	},
	{
		id: 8,
		label: 'accessories',
		directory: 'accessories',
		selected: false,
		items: [
			{ id: 0, label: 'default', fileName: 'default', selected: false },
			{ id: 1, label: 'earings', fileName: 'earings', selected: false },
			{ id: 2, label: 'flower', fileName: 'flower', selected: false },
			{ id: 3, label: 'glasses', fileName: 'glasses', selected: false },
		],
	},
];
